"""added sold to post

Revision ID: 3098c871a8cb
Revises: ba5f1aa09d5f
Create Date: 2022-04-18 21:14:10.662288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3098c871a8cb'
down_revision = 'ba5f1aa09d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('post', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key('post', 'card', ['card'], ['id'])
        batch_op.drop_column('sold')

    # ### end Alembic commands ###
