"""added relationship comment to post

Revision ID: 46ad2ab950d6
Revises: d71e5a774a6c
Create Date: 2022-04-18 16:13:31.697107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ad2ab950d6'
down_revision = 'd71e5a774a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('post_id', 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('post_id', type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
