"""add date column for comment

Revision ID: 48b527ea7679
Revises: 7f6af9a4979e
Create Date: 2022-04-18 20:19:57.728604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b527ea7679'
down_revision = '7f6af9a4979e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key('post', 'card', ['card'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('post', type_='foreignkey')

    # ### end Alembic commands ###
