"""card relation to post

Revision ID: ba5f1aa09d5f
Revises: 48b527ea7679
Create Date: 2022-04-18 20:35:21.929378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5f1aa09d5f'
down_revision = '48b527ea7679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('date_posted',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('date_posted',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('date_posted',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('date_posted',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
