"""added relationship comment to user

Revision ID: d71e5a774a6c
Revises: 45bdbc311cce
Create Date: 2022-04-18 16:09:12.227829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71e5a774a6c'
down_revision = '45bdbc311cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
