"""add relationship to post

Revision ID: dacd6099f50a
Revises: e33aa37e2b89
Create Date: 2022-04-18 16:22:01.560893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dacd6099f50a'
down_revision = 'e33aa37e2b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('post_id', 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('post_id', type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
