"""remove relationship

Revision ID: e33aa37e2b89
Revises: 46ad2ab950d6
Create Date: 2022-04-18 16:16:46.908541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33aa37e2b89'
down_revision = '46ad2ab950d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('user_id', type_='foreignkey')
        batch_op.drop_constraint('post_id', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('post_id', 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key('user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
