import difflib

# # # Ex 1
# # numbers = [5, 10, 15, 20, 25, 50, 20]
# #
# # index_num = numbers.index(20)
# # numbers[index_num] = 200
# # print(numbers)
#
# # my_tuple = (1, 3)
# # my_list = [5, 6]
# #
# # myNum1, myNum2 = my_list
# #
# # print(myNum1)
# # print(myNum2)
#
# # # Ex 2
#
# aTuple = (10, 20, 30, 40)
# num1,num2,num3,num4 = aTuple
# print(num1, num2, num3, num4)
#
# print("")
# num = 0
#
# print("")
# for i in aTuple:
#     print(i)
#
# print("")
# for index in range(0, len(aTuple)):
#     print(f"#{index+1}: {aTuple[index-1]}")
#
#
# userIn = input("userIn = input")
#
# while not (userIn == "hello"):
#     print("wrong pass try again")
#     userIn = input("Enter a password: ")
#
#
# multiplyNum = int(input("Enter a number: "))
# counter = 0
#
# for i in range(1, 13):
#     print(f"{i} * {multiplyNum} = {multiplyNum * i}")
#
# print("")
# while counter <= 12:
#     print(f"{counter} * {multiplyNum} = {multiplyNum * counter}")
#     counter += 1


# Scroll to bottom to see solution
# You are working for the school Principal. We have a database of school students:


# during class, the teachers take attendance and compile it into a list.


# using what you learned about sets, create a piece of code that the school principal can use to immediately find out who missed class so they can call the parents. (Imagine if the list had 1000s of students. The principal can use the lists generated by the teachers + the school database to use python and make his/her job easier): Find the students that miss class!

school = {'Bobby', 'Tammy', 'Jammy', 'Sally', 'Danny'}
attendance_list = ['Jammy', 'Bobby', 'Danny', 'Sally']
attendance_set = set(attendance_list)

print(attendance_set)
print(school.difference(attendance_list))
