"""empty message

Revision ID: 504ae14fd3d7
Revises: 
Create Date: 2022-03-27 17:42:04.694018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504ae14fd3d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
